language: node_js
node_js:
  - 0.11
before_script:
  - npm install -g grunt-cli
after_script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=JhpGymUC5TwpZd6JKfGeqVlLtGMxKhyvF
  - npm install -g istanbul
  - istanbul cover dist/node-test-cli.js --report lcovonly -- -R spec
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js